name: Sample workflow for Firebase Distribution action
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: apk-build
          path: build/app/outputs/bundle/release
      - name: Deploy
        if: (github.base_ref == 'main' && github.event_name == 'pull_request')
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APPID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: Testers
          release_notes: "a new version"
          file: build/app/outputs/apk/release/app-release.apk
